name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - uses: microsoft/playwright-github-action@v1
    - name: Install dependencies and run tests
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum npm test
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal --logger "nunit;LogFileName=TestResults.xml"
