name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - uses: microsoft/playwright-github-action@v1
    - uses: actions/setup-node@v2
      with:
          node-version: '14.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Install Playwright Test
      run: 
          npm install -D @playwright/test
    - name: Install Playwright
      run: | 
          npx playwright install --with-deps     
    - name: Build
      run: dotnet build --no-restore
    - name: Run API Tests        
      run: dotnet test Bnz.API.Tests --verbosity normal --logger "nunit;LogFileName=TestResults.xml"
    - name: Run UI Tests
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- bash -c "npm run test" --headed
